### ISSUE TITLE
有没有兴趣创作开放、成套的女书黑体？

### ISSUE THREAD

**Issue by MY1L** [nushu-script/rime-unicode_nushu#1]
“黑体”指无衬线字体。而我正在制作一套无衬线字体（常规+粗体，见我的github），如果有人有这样的打算，说不定可以帮上忙。

可能此时有人已经在做，但我在[The Nushu Coder's Group on GitHub](https://github.com/nushu-script/)没看到字体相关的项目，而我也没有Telegram，所以发在这里了（毕竟没有字体的话，输入法就没法用）

**Comment by sgalal** [comment]
<span lang="zh-CN">谢谢，很有兴趣！如果你想制作，我将尽力提供帮助。</span>

**Comment by MY1L** [comment]
;)
