### ISSUE TITLE
macOS安装后无法使用

### ISSUE THREAD

**Issue by Asimash37** [nushu-script/rime-unicode_nushu#2]
您好，
安装点击「重新部署」和「同步用户数据」系统没有反应？使用Ctrl + `后选项里也没有找到女书

![image](https://user-images.githubusercontent.com/69827598/91044003-ef53a100-e657-11ea-974b-01584f014852.png)
![image](https://user-images.githubusercontent.com/69827598/91044021-f67aaf00-e657-11ea-873e-eb072a2a45ff.png)

**Comment by sgalal** [comment]
```sh
curl -fsSL https://git.io/rime-install | bash -s -- nushu-script/rime-nushu custom:set:config=default,key=installed_from,value=nushu-script/rime-nushu custom:add:schema=nushu custom:add:schema=luna_pinyin_nushu
```

这一步成功了吗？Terminal 里有没有什么输出或者错误信息？

**Comment by Asimash37** [comment]
> ```shell
> curl -fsSL https://git.io/rime-install | bash -s -- nushu-script/rime-nushu custom:set:config=default,key=installed_from,value=nushu-script/rime-nushu custom:add:schema=nushu custom:add:schema=luna_pinyin_nushu
> ```
> 
> 这一步成功了吗？Terminal 里有没有什么输出或者错误信息？

感谢您的及时回复:) 
我的电脑好像是在terminal运行之后直接跳转去下载git了，下载完我以为已经装好了就直接选择了输入法...刚刚重新在terminal里做了一遍就全部修复了~ 谢谢啦
